#!/usr/bin/env python3
# -*- coding: utf-8 -*-


OwnerMatch = {
    'Atlanta Hawks': 'Neil', 
    'Boston Celtics': 'Zack', 
    'Brooklyn Nets': 'Ian', 
    'Charlotte Hornets': None, 
    'Chicago Bulls': None, 
    'Cleveland Cavaliers': None, 
    'Dallas Mavericks': 'Grant', 
    'Denver Nuggets': 'Simar', 
    'Detroit Pistons': None, 
    'Golden State Warriors': None, 
    'Houston Rockets': 'John', 
    'Indiana Pacers': 'Griffin', 
    'Los Angeles Clippers': 'Sebastian', 
    'Los Angeles Lakers': 'Ian', 
    'Memphis Grizzlies': None, 
    'Miami Heat': 'Eric', 
    'Milwaukee Bucks': 'Neil', 
    'Minnesota Timberwolves': 'Simar', 
    'New Orleans Pelicans': None, 
    'New York Knicks': None, 
    'Oklahoma City Thunder': 'Dawson', 
    'Orlando Magic': 'John', 
    'Philadelphia 76ers': 'Dawson', 
    'Phoenix Suns': 'Zack', 
    'Portland Trail Blazers': 'Sebastian', 
    'Sacramento Kings': None, 
    'San Antonio Spurs': 'Eric', 
    'Toronto Raptors': 'Grant', 
    'Utah Jazz': 'Griffin', 
    'Washington Wizards': None
    }

RoundMatch = {
    'Atlanta Hawks': 'Round 2', 
    'Boston Celtics': 'Round 1', 
    'Brooklyn Nets': 'Round 2', 
    'Charlotte Hornets': None, 
    'Chicago Bulls': None, 
    'Cleveland Cavaliers': None, 
    'Dallas Mavericks': 'Round 2', 
    'Denver Nuggets': 'Round 1', 
    'Detroit Pistons': None, 
    'Golden State Warriors': None, 
    'Houston Rockets': 'Round 1', 
    'Indiana Pacers': 'Round 2', 
    'Los Angeles Clippers': 'Round 1', 
    'Los Angeles Lakers': 'Round 1', 
    'Memphis Grizzlies': None, 
    'Miami Heat': 'Round 1', 
    'Milwaukee Bucks': 'Round 1', 
    'Minnesota Timberwolves': 'Round 2', 
    'New Orleans Pelicans': None, 
    'New York Knicks': None, 
    'Oklahoma City Thunder': 'Round 2', 
    'Orlando Magic': 'Round 2', 
    'Philadelphia 76ers': 'Round 1', 
    'Phoenix Suns': 'Round 2', 
    'Portland Trail Blazers': 'Round 2', 
    'Sacramento Kings': None, 
    'San Antonio Spurs': 'Round 2', 
    'Toronto Raptors': 'Round 1', 
    'Utah Jazz': 'Round 1', 
    'Washington Wizards': None
    }